version: '3'
services:
  db:
    image: postgres:16
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    networks:
      - nat
    volumes:
      - postgres_v:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - nat

networks:
  nat:
    driver: bridge

volumes:
  postgres_v:
    driver_opts:
      type: none
      device: /Users/hed-dyb/Desktop/db
      o: bind
